version: 2
updates:
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "docker"
      - "dependencies"

  # NPM dependencies for emtu-web
  - package-ecosystem: "npm"
    directory: "/emtu-web"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "npm"
      - "dependencies"

  # NPM dependencies for emtu-api
  - package-ecosystem: "npm"
    directory: "/emtu-api"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "npm"
      - "dependencies"

  # NPM dependencies for plasmedis-web
  - package-ecosystem: "npm"
    directory: "/plasmedis-web"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "npm"
      - "dependencies"

  # Python dependencies for plasmedis-api
  - package-ecosystem: "pip"
    directory: "/plasmedis-api"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "pip"
      - "dependencies"
